"""empty message

Revision ID: 726a7798f587
Revises: 
Create Date: 2020-10-23 10:03:04.132633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726a7798f587'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('nn1', sa.String(), nullable=True),
    sa.Column('nn2', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pos1', sa.String(), nullable=True),
    sa.Column('pos2', sa.String(), nullable=True),
    sa.Column('neg1', sa.String(), nullable=True),
    sa.Column('neg2', sa.String(), nullable=True),
    sa.Column('new1', sa.String(), nullable=True),
    sa.Column('new2', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    op.drop_table('user')
    # ### end Alembic commands ###
